# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2674d7867d78f7fc78de1fe8498b4d563466401ed39411abfffea0bb49a791ed9f3193b93edfbb78665792af39161d05c8ba2e6c88cd5892d65e6060fc6e6950

test:
  secret_key_base: 002ce98e6f76e1461286e35530eeff58eabc81785e52bd039aeae0dc4dba76b10f69614902c15c5b52c5bec77525918fc75698d1ebc7e837f0d9b84d56d40005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
